### ISSUE TITLE
Crash on opening GUI in Linux

### ISSUE THREAD

**Issue by ctsexton** [reales/OB-Xd#37]
I am getting a segmentation fault if I try to open the GUI in Ardour and Carla.

Audio works fine, and I can edit plugin parameters using the generic UI provided by Ardour, but as soon as I try to open the OB-Xd UI - immediate seg fault.

Using Arch Linux and the binaries provided here: https://www.discodsp.com/obxd/

**Comment by usrfriendly** [comment]
Different platform and software(s), but possibly related: in Windows it tanks Reaper, and Renoise returns "discoDSP: OB-Xd (from DiscoDSP) crashed in VST event/fuction: 'Dispatch', Thread: 'GUI'

I used the installer from github.

**Comment by meganerd** [comment]
OK, I had the same problem on Ubuntu 20.10.  It turns out that I had not run the install.sh script, which copies files and documents into your ~/Documents/discoDSP/OB-Xd/ folder.  The hint came from running it with strace, which gives this output:

> stat("/home/<my_user>/Documents", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
readlink("/home/<my_user>/Documents/discoDSP/OB-Xd", 0x1e897d0, 8192) = -1 ENOENT (No such file or directory)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x168} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
