### ISSUE TITLE
Load preset and skin files not only from C:\Users\User\Documents\discoDSP

### ISSUE THREAD

**Issue by josephernest** [reales/OB-Xd#5]
By default, the Skins and Banks are searched in:

    C:\Users\User\Documents\discoDSP\OB-Xd\Banks
    C:\Users\User\Documents\discoDSP\OB-Xd\Skins

**Question: can OB-Xd search for them in the same folder than the .dll?**

Example:

    D:\VstPlugins\Instruments\Obxd.dll             # the main file
    D:\VstPlugins\Instruments\discoDSP\OB-Xd\Banks
    D:\VstPlugins\Instruments\discoDSP\OB-Xd\Skins

(Very useful for "portable" usage of the VST, i.e. no need to reinstall after computer format, we just keep the `D:\VstPlugins`. It works with most freeware VST.)

**Comment by reales** [comment]
Reinstall is not necessary. Placing OB-Xd folder at Documents\discoDSP\ is enough.

**Comment by wibblemonkey** [comment]
I would really like to see this feature as well - I use a portable installation of Reaper on a USB flash drive so that I can use it on PCs where I don't have permission to install 3rd party software. I have a collection of free VSTs on the same drive, but I can't currently include OB-Xd because it expects its data files to be in the Document folder on the PC, rather than on the flash drive with the DLL.
The behaviour requested is pretty much exactly what Dexed does: check the folder containing the plugin DLL first and if the folder doesn't exist, fall back to using the Documents folder as it currently does:
https://github.com/asb2m10/dexed/blob/60bb86bd254b03e9293480a8f638b6e6c5c66780/Source/PluginData.cpp#L455

**Comment by JamesFrederik** [comment]
I'd like to be able to change the location on Linux too.

Having it in /Documents is messy

I'd like to put it in .local or .config or just the root of /home
