### ISSUE TITLE
License Issue

### ISSUE THREAD

**Issue by LoveBodhi** [reales/OB-Xd#66]
"OB-Xd Desktop is free for non-commercial use." but source code is GPL v3 so......

**Comment by reales** [comment]
You can charge a fee for software covered by the GNU GPL. The GPL license does not forbid you to ask money for obtaining your program.

**Comment by arthurthefourth** [comment]
I don't think that's the issue here. You can absolutely charge for distributing the software (and I wouldn't begrudge you that, given the work you're putting into it), but as I understand it, the GPL doesn't allow you to limit the use of the software once you've distributed it. See https://opensource.stackexchange.com/a/7399
